name: 'Update DDNS'
description: 'DDNS(Distributed Domain Name System) update action. Currently it supports ENS and CNS.'
branding:
  icon: 'edit'
  color: 'green'
inputs:
  mnemonic:
    description: 'Mnemonic phrase for wallet recovery. Plain PrivateKey can be used as well.'
    required: true
  rpc:
    description: 'Url of RPC APIs.'
    required: true
  name:
    description: 'Distributed domain name. Currently it supports ENS, CNS (.eth, .crypto) names. (eg `ddns-action.eth`)'
    required: true
  contentHash:
    description: 'Hash of content.'
    required: true
  contentType:
    description: 'Type of content. Supported types [ipfs-ns, swarm-ns]'
    required: false
    default: 'ipfs-ns'
  gasPrice:
    description: 'Gas price'
    required: false
    default: 10000000000
  dryRun: 
    description: 'Execution emulation without setting new content hash.'
    required: false
    default: false
  verbose:
    description: 'Level of verbosity'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'index.js'